/**
 * Provider — inference engine trait.
 *
 * Every LLM backend (Anthropic, OpenAI, LiteLLM, etc.) implements this
 * interface. The agent loop calls `chat()` and streams back `ChatChunk`s.
 *
 * Providers handle:
 * - Model routing via `provider/model` refs (e.g. 'anthropic/claude-sonnet-4-6')
 * - API key rotation and failover
 * - Streaming-first responses via AsyncIterable
 * - Message format conversion to/from provider-specific APIs
 *
 * @example
 * ```typescript
 * const provider = new AnthropicProvider();
 * for await (const chunk of provider.chat({ model: 'claude-sonnet-4-6', messages, stream: true })) {
 *   if (chunk.text) process.stdout.write(chunk.text);
 * }
 * ```
 */

// ─── Request / Response types ───────────────────────────────────────

/** A single message in the conversation history. */
export interface ChatMessage {
  /** Message role: system prompt, user input, assistant response, or tool result */
  role: 'system' | 'user' | 'assistant' | 'tool';
  /** Content as plain text or structured content parts (for tool_use blocks) */
  content: string | ContentPart[];
  /** Optional display name for the message author */
  name?: string;
  /** For tool-role messages: the ID of the tool_use block this result corresponds to */
  tool_call_id?: string;
}

/**
 * A structured content part within a message.
 * Used for multi-modal messages (text + images) and tool interactions.
 */
export type ContentPart =
  | { type: 'text'; text: string }
  | { type: 'image_url'; image_url: { url: string } }
  | { type: 'image_base64'; media_type: string; data: string }
  | { type: 'document'; source: { type: 'base64'; media_type: string; data: string } }
  | { type: 'tool_use'; id: string; name: string; input: unknown }
  | { type: 'tool_result'; tool_use_id: string; content: string };

/** A tool definition sent to the model for function calling. */
export interface ToolDefinition {
  /** Unique tool name */
  name: string;
  /** Human-readable description of what the tool does */
  description: string;
  /** JSON Schema describing the tool's input parameters */
  parameters: Record<string, unknown>;
}

/** Request payload for a chat completion. */
export interface ChatRequest {
  /** Model identifier (e.g. 'claude-sonnet-4-6' or 'anthropic/claude-sonnet-4-6') */
  model: string;
  /** Conversation history including system prompt */
  messages: ChatMessage[];
  /** Available tools for function calling */
  tools?: ToolDefinition[];
  /** Sampling temperature (0.0 = deterministic, 1.0 = creative) */
  temperature?: number;
  /** Maximum tokens to generate */
  max_tokens?: number;
  /** Stop sequences that halt generation */
  stop?: string[];
  /** Whether to stream the response (default: true) */
  stream?: boolean;
  /** Anthropic prompt cache retention mode (passed through to provider). */
  cacheRetention?: 'none' | 'short' | 'long';
}

/** A tool call requested by the model during generation. */
export interface ToolCall {
  /** Unique ID for this tool call (used to match results) */
  id: string;
  /** Name of the tool to invoke */
  name: string;
  /** Parsed input parameters for the tool */
  input: unknown;
}

/** A single chunk in a streaming chat response. */
export interface ChatChunk {
  /** Incremental text delta (may be empty on tool-call-only chunks) */
  text?: string;
  /** Tool calls emitted by the model (accumulated across chunks) */
  tool_calls?: ToolCall[];
  /** True on the final chunk — signals end of generation */
  done: boolean;
  /** Token usage statistics (populated on the final chunk only) */
  usage?: UsageStats;
}

/** Token usage statistics for a chat completion. */
export interface UsageStats {
  /** Number of tokens in the input (system + messages + tools) */
  prompt_tokens: number;
  /** Number of tokens generated by the model */
  completion_tokens: number;
  /** Total tokens consumed (prompt + completion) */
  total_tokens: number;
  /** Tokens written to cache on this request (Anthropic prompt caching). */
  cache_creation_input_tokens?: number;
  /** Tokens read from cache on this request (Anthropic prompt caching). */
  cache_read_input_tokens?: number;
}

/** Information about an available model. */
export interface ModelInfo {
  /** Model identifier (e.g. 'claude-sonnet-4-6') */
  id: string;
  /** Human-readable model name */
  name: string;
  /** Provider that serves this model */
  provider: string;
  /** Maximum input context window in tokens */
  context_window: number;
  /** Maximum output tokens the model can generate */
  max_output_tokens: number;
  /** Supported capabilities (e.g. 'vision', 'tools', 'streaming') */
  capabilities: string[];
}

// ─── Provider interface ─────────────────────────────────────────────

/**
 * Provider — the inference engine trait.
 *
 * Implementations adapt a specific LLM API (Anthropic, OpenAI, LiteLLM)
 * into Tako's unified streaming interface. The agent loop depends only
 * on this interface, making providers fully swappable.
 *
 * Built-in implementations:
 * - {@link AnthropicProvider} — native Anthropic API with key rotation
 * - {@link OpenAIProvider} — OpenAI-compatible API
 * - {@link LiteLLMProvider} — proxy to 100+ providers
 */
export interface Provider {
  /** Unique provider identifier (e.g. 'anthropic', 'openai', 'litellm') */
  id: string;

  /**
   * Stream a chat completion.
   *
   * Always returns an async iterable of chunks, even for non-streaming requests.
   * The final chunk has `done: true` and includes usage statistics.
   *
   * @param req - The chat request including model, messages, and tools
   * @returns Async iterable of response chunks
   */
  chat(req: ChatRequest): AsyncIterable<ChatChunk>;

  /**
   * List models available through this provider.
   *
   * @returns Array of model information objects
   */
  models(): ModelInfo[];

  /**
   * Check if this provider supports a given capability.
   *
   * @param capability - Capability name (e.g. 'vision', 'tools', 'streaming')
   * @returns True if the capability is supported
   */
  supports(capability: string): boolean;
}
